export enum OtpTemplateType {
  REGISTRATION = 'REGISTRATION',
  RESEND = 'RESEND',
  FORGOT_PASSWORD = 'FORGOT_PASSWORD',
  PASSWORD_CHANGED = 'PASSWORD_CHANGED',
  PASSWORD_RESET = 'PASSWORD_RESET',
  NEW_LOGIN = 'NEW_LOGIN',
}
